### ISSUE TITLE
[IOS] Reading book not working

### ISSUE THREAD

**Issue by minh-dai** [Mantano/iridium#111]
![Screenshot 2024-05-11 at 14 41 38](https://github.com/Mantano/iridium/assets/24986640/478441ff-3c75-45c8-b2e9-491d23a92880)

======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building FutureBuilder<bool>(dirty, state: _FutureBuilderState<bool>#425cc):
Null check operator used on a null value

The relevant error-causing widget was: 
  EpubScreen EpubScreen:file:///Users/minhdai/Desktop/FlutterProject/iridium/demo-app/lib/views/details/details.dart:228:20
When the exception was thrown, this was the stack: 
#0      BookScreenState.build.<anonymous closure> (package:iridium_reader_widget/views/viewers/book_screen.dart:86:26)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#12     _invoke (dart:ui/hooks.dart:312:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#14     _drawFrame (dart:ui/hooks.dart:283:31)

Flutter: 3.19.6

**Comment by minh-dai** [comment]
I think you need to read this link:

https://inappwebview.dev/docs/debugging-webviews/#inspect-android-webviews

**Comment by jmgeffroy** [comment]
Hi @minh-dai, thanks for the report. Sorry for the delay, I'm really overwhelmed with a huge project. I just pushed a commit that fixes this issue.
Cheers
